# Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

#RestTemplate
greencityuser.server.address=http://localhost:8080

# Token expiration time
tokenKey=1
accessTokenValidTimeInMinutes=120
refreshTokenValidTimeInMinutes=600
verifyEmailTimeHour=24

greencity.images.strategy=database

# Aws S3 configuration
aws.s3.accessKey=${AWS_ACCESS_KEY}
aws.s3.secretKey=${AWS_SECRET_KEY}
aws.s3.region=us-east-1
aws.s3.bucketName=green-city-images-bucket

